services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.modular
    image: busybox-network-mcp
    container_name: busybox-network-mcp
    ports:
      - "3000:3000"
      - "161:161/udp" # SNMP port
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    cpus: 0.5
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
