import { z } from 'zod';

import { ResponseFormatSchema, type ResponseFormat, type ToolResponse } from './shared';

export { ResponseFormatSchema };
export type { ResponseFormat, ToolResponse };

export interface ToolAnnotationHints {
  [key: string]: unknown;
  readOnlyHint: boolean;
  destructiveHint: boolean;
  idempotentHint: boolean;
  openWorldHint: boolean;
}

export const ZabbixReadAnnotations: ToolAnnotationHints = {
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: false,
  openWorldHint: true,
};

export const ZabbixIdempotentReadAnnotations: ToolAnnotationHints = {
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
};

export const CredentialsShape = {
  baseUrl: z.string().optional().describe('Zabbix server base URL'),
  username: z.string().optional().describe('Zabbix username for authentication'),
  password: z.string().optional().describe('Zabbix password for authentication'),
} satisfies z.ZodRawShape;

export const HostDiscoverInputShape = {
  ...CredentialsShape,
  groupFilter: z.string().optional().describe('Filter hosts by group name'),
  templateFilter: z.string().optional().describe('Filter hosts by template name'),
  limit: z.number().optional().describe('Maximum number of hosts to return'),
  response_format: ResponseFormatSchema,
} satisfies z.ZodRawShape;

export const MetricsInputShape = {
  ...CredentialsShape,
  hostName: z.string().describe('Hostname to retrieve metrics for'),
  itemFilter: z.string().optional().describe('Filter items by name pattern'),
  timeFrom: z.string().optional().describe('Start time for historical data'),
  timeTill: z.string().optional().describe('End time for historical data'),
  limit: z.number().optional().describe('Maximum number of items to return'),
  response_format: ResponseFormatSchema,
} satisfies z.ZodRawShape;

export const AlertsInputShape = {
  ...CredentialsShape,
  hostFilter: z.string().optional().describe('Filter alerts by hostname'),
  actionIds: z.array(z.string()).optional().describe('Return only alerts generated by specific actions'),
  eventIds: z.array(z.string()).optional().describe('Return only alerts generated by specific events'),
  limit: z.number().optional().describe('Maximum number of alerts to return'),
  response_format: ResponseFormatSchema,
} satisfies z.ZodRawShape;

export const InventoryInputShape = {
  ...CredentialsShape,
  hostFilter: z.string().optional().describe('Filter hosts by name pattern'),
  inventoryMode: z.enum(['automatic', 'manual', 'disabled']).optional().describe('Filter by inventory mode'),
  limit: z.number().optional().describe('Maximum number of hosts to return'),
  response_format: ResponseFormatSchema,
} satisfies z.ZodRawShape;

export const ProblemsInputShape = {
  ...CredentialsShape,
  hostFilter: z.string().optional().describe('Filter problems by hostname'),
  severityFilter: z.enum(['not_classified', 'information', 'warning', 'average', 'high', 'disaster']).optional().describe('Filter by severity level'),
  acknowledged: z.boolean().optional().describe('Filter by acknowledgment status'),
  recent: z.boolean().optional().describe('Show only recent problems'),
  limit: z.number().optional().describe('Maximum number of problems to return'),
  response_format: ResponseFormatSchema,
} satisfies z.ZodRawShape;

export const EventsInputShape = {
  ...CredentialsShape,
  hostFilter: z.string().optional().describe('Filter events by hostname'),
  eventType: z.enum(['trigger', 'discovery', 'autoregistration', 'internal']).optional().describe('Filter by event source type'),
  timeFrom: z.string().optional().describe('Start time for events'),
  timeTill: z.string().optional().describe('End time for events'),
  acknowledged: z.boolean().optional().describe('Filter by acknowledgment status'),
  limit: z.number().optional().describe('Maximum number of events to return'),
  response_format: ResponseFormatSchema,
} satisfies z.ZodRawShape;

export const TriggersInputShape = {
  ...CredentialsShape,
  hostFilter: z.string().optional().describe('Filter triggers by hostname'),
  statusFilter: z.enum(['enabled', 'disabled']).optional().describe('Filter by trigger status'),
  severityFilter: z.enum(['not_classified', 'information', 'warning', 'average', 'high', 'disaster']).optional().describe('Filter by trigger severity'),
  activeOnly: z.boolean().optional().describe('Show only triggers with active problems'),
  templated: z.boolean().optional().describe('Include templated triggers'),
  limit: z.number().optional().describe('Maximum number of triggers to return'),
  response_format: ResponseFormatSchema,
} satisfies z.ZodRawShape;

export interface ZabbixClientConfig {
  baseUrl: string;
  username: string;
  password: string;
}

export interface JsonRpcRequest<T> {
  jsonrpc: '2.0';
  method: string;
  params: T;
  id: number;
  auth?: string;
}

export interface JsonRpcError {
  code: number;
  message: string;
}

export interface JsonRpcResponse<T> {
  result?: T;
  error?: JsonRpcError;
}