"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TriggersInputShape = exports.EventsInputShape = exports.ProblemsInputShape = exports.InventoryInputShape = exports.AlertsInputShape = exports.MetricsInputShape = exports.HostDiscoverInputShape = exports.CredentialsShape = exports.ZabbixIdempotentReadAnnotations = exports.ZabbixReadAnnotations = exports.ResponseFormatSchema = void 0;
const zod_1 = require("zod");
const shared_1 = require("./shared");
Object.defineProperty(exports, "ResponseFormatSchema", { enumerable: true, get: function () { return shared_1.ResponseFormatSchema; } });
exports.ZabbixReadAnnotations = {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: true,
};
exports.ZabbixIdempotentReadAnnotations = {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: true,
};
exports.CredentialsShape = {
    baseUrl: zod_1.z.string().optional().describe('Zabbix server base URL'),
    username: zod_1.z.string().optional().describe('Zabbix username for authentication'),
    password: zod_1.z.string().optional().describe('Zabbix password for authentication'),
};
exports.HostDiscoverInputShape = {
    ...exports.CredentialsShape,
    groupFilter: zod_1.z.string().optional().describe('Filter hosts by group name'),
    templateFilter: zod_1.z.string().optional().describe('Filter hosts by template name'),
    limit: zod_1.z.number().optional().describe('Maximum number of hosts to return'),
    response_format: shared_1.ResponseFormatSchema,
};
exports.MetricsInputShape = {
    ...exports.CredentialsShape,
    hostName: zod_1.z.string().describe('Hostname to retrieve metrics for'),
    itemFilter: zod_1.z.string().optional().describe('Filter items by name pattern'),
    timeFrom: zod_1.z.string().optional().describe('Start time for historical data'),
    timeTill: zod_1.z.string().optional().describe('End time for historical data'),
    limit: zod_1.z.number().optional().describe('Maximum number of items to return'),
    response_format: shared_1.ResponseFormatSchema,
};
exports.AlertsInputShape = {
    ...exports.CredentialsShape,
    hostFilter: zod_1.z.string().optional().describe('Filter alerts by hostname'),
    actionIds: zod_1.z.array(zod_1.z.string()).optional().describe('Return only alerts generated by specific actions'),
    eventIds: zod_1.z.array(zod_1.z.string()).optional().describe('Return only alerts generated by specific events'),
    limit: zod_1.z.number().optional().describe('Maximum number of alerts to return'),
    response_format: shared_1.ResponseFormatSchema,
};
exports.InventoryInputShape = {
    ...exports.CredentialsShape,
    hostFilter: zod_1.z.string().optional().describe('Filter hosts by name pattern'),
    inventoryMode: zod_1.z.enum(['automatic', 'manual', 'disabled']).optional().describe('Filter by inventory mode'),
    limit: zod_1.z.number().optional().describe('Maximum number of hosts to return'),
    response_format: shared_1.ResponseFormatSchema,
};
exports.ProblemsInputShape = {
    ...exports.CredentialsShape,
    hostFilter: zod_1.z.string().optional().describe('Filter problems by hostname'),
    severityFilter: zod_1.z.enum(['not_classified', 'information', 'warning', 'average', 'high', 'disaster']).optional().describe('Filter by severity level'),
    acknowledged: zod_1.z.boolean().optional().describe('Filter by acknowledgment status'),
    recent: zod_1.z.boolean().optional().describe('Show only recent problems'),
    limit: zod_1.z.number().optional().describe('Maximum number of problems to return'),
    response_format: shared_1.ResponseFormatSchema,
};
exports.EventsInputShape = {
    ...exports.CredentialsShape,
    hostFilter: zod_1.z.string().optional().describe('Filter events by hostname'),
    eventType: zod_1.z.enum(['trigger', 'discovery', 'autoregistration', 'internal']).optional().describe('Filter by event source type'),
    timeFrom: zod_1.z.string().optional().describe('Start time for events'),
    timeTill: zod_1.z.string().optional().describe('End time for events'),
    acknowledged: zod_1.z.boolean().optional().describe('Filter by acknowledgment status'),
    limit: zod_1.z.number().optional().describe('Maximum number of events to return'),
    response_format: shared_1.ResponseFormatSchema,
};
exports.TriggersInputShape = {
    ...exports.CredentialsShape,
    hostFilter: zod_1.z.string().optional().describe('Filter triggers by hostname'),
    statusFilter: zod_1.z.enum(['enabled', 'disabled']).optional().describe('Filter by trigger status'),
    severityFilter: zod_1.z.enum(['not_classified', 'information', 'warning', 'average', 'high', 'disaster']).optional().describe('Filter by trigger severity'),
    activeOnly: zod_1.z.boolean().optional().describe('Show only triggers with active problems'),
    templated: zod_1.z.boolean().optional().describe('Include templated triggers'),
    limit: zod_1.z.number().optional().describe('Maximum number of triggers to return'),
    response_format: shared_1.ResponseFormatSchema,
};
//# sourceMappingURL=types.js.map