# Zabbix Testing Environment for MCP Open Discovery
# This provides a complete Zabbix stack for testing our integration
# Uses the same network as the main MCP server and SNMP test agents

version: '3.8'

services:
  # PostgreSQL database for Zabbix
  postgres-zabbix:
    image: postgres:15-alpine
    container_name: zabbix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - zabbix-postgres-data:/var/lib/postgresql/data
    networks:
      mcp-open-discovery_mcp-network:
        ipv4_address: 172.20.0.20
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      postgres-zabbix:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_PROXYCONFIGFREQUENCY: 3600
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-server-enc:/var/lib/zabbix/enc
      - zabbix-server-ssh:/var/lib/zabbix/ssh_keys
      - zabbix-server-ssl:/var/lib/zabbix/ssl
    networks:
      mcp-open-discovery_mcp-network:
        ipv4_address: 172.20.0.21
    ports:
      - "10051:10051"
    healthcheck:
      test: ["CMD-SHELL", "zabbix_get -s 127.0.0.1 -k agent.ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Zabbix Web Interface
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgres-zabbix
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      PHP_TZ: America/New_York
    volumes:
      - zabbix-web-ssl:/etc/ssl/nginx
    networks:
      mcp-open-discovery_mcp-network:
        ipv4_address: 172.20.0.22
    ports:
      - "8080:8080"
      - "8443:8443"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Zabbix Agent (for testing)
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "Zabbix Test Agent"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_PASSIVE_ALLOW: true
      ZBX_ACTIVE_ALLOW: true
      ZBX_DEBUGLEVEL: 3
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    pid: "host"
    networks:
      mcp-open-discovery_mcp-network:
        ipv4_address: 172.20.0.23
    ports:
      - "10050:10050"

  # Additional test agent (simulates another monitored host)
  zabbix-agent-2:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: zabbix-agent-2
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "Test Web Server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_PASSIVE_ALLOW: true
      ZBX_ACTIVE_ALLOW: true
      ZBX_DEBUGLEVEL: 3
    networks:
      mcp-open-discovery_mcp-network:
        ipv4_address: 172.20.0.24
    ports:
      - "10052:10050"

  # NGINX web server (simulates a monitored web service)
  nginx-test:
    image: nginx:alpine
    container_name: nginx-test-server
    restart: unless-stopped
    volumes:
      - ./test-data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./test-data/html:/usr/share/nginx/html:ro
    networks:
      mcp-open-discovery_mcp-network:
        ipv4_address: 172.20.0.25
    ports:
      - "8888:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  zabbix-postgres-data:
    driver: local
  zabbix-server-data:
    driver: local
  zabbix-server-enc:
    driver: local
  zabbix-server-ssh:
    driver: local
  zabbix-server-ssl:
    driver: local
  zabbix-web-ssl:
    driver: local

networks:
  mcp-open-discovery_mcp-network:
    external: true
